import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ShimmerButton } from "@/components/magicui/shimmer-button";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased dark container mx-auto`}>
        <header className="flex w-full justify-between items-center p-6 px-18">
          <div>
            <h1 className="text-2xl font-bold">Liro</h1>
          </div>
          <nav className="flex gap-8">
            <a href="/">Home</a>
            <a href="/about">About</a>
            <a href="/services">Services</a>
            <a href="/blog">Blog</a>
          </nav>
          <div>
            <ShimmerButton className="text-white! text-sm">
              Contact Us!
            </ShimmerButton>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
